config/routes.rb
Diplom::Application.routes.draw do

  get "student_groups/index"

  get "student_groups/show"

  get "students/index"

  get "students/show"

  get "documents/show"

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => 'home#index'

  resources :courses, :only => [:index, :show] do
    resources :lessons, :only => [:index, :show] do
      resources :testings do
        member do
          get :next
          get :results
        end
      end
      member do
        get :videos
        get :documents
        get :tests
      end
    end
  end

  resources :documents, only: :show

  resources :teachers do
    resources :students, :student_groups, :courses
  end

  resources :user_courses do
    collection do 
      post :bulk
    end
  end

  resources :categories, :study_rooms

  match 'search' => 'courses#search', :as => :search

  

  resources :statistics do
    member do
      get :courses
      get :testings
      get :questions
    end
    collection do
      get :passed
      get :failed
      get :new_courses
    end
  end

  resources :videos do
    member do
      post :add_comment
    end     
    new do
       post :upload
       get  :save_video
     end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)              
    if user && user.role == "admin"
      can :manage, :all
    else

    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :courses, :dependent => :nullify

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :category
  has_many :user_courses
  has_many :users, :through => :user_courses

  has_many :lessons, :dependent => :destroy

  has_many :student_group_courses
  has_many :student_groups, :through => :student_group_courses

  has_many :user_testings
  has_many :testings, :through => :user_testings

  has_many :user_lessons

  has_many :videos, :through => :lessons
  has_many :documents, :through => :lessons

  scope :passed, where(:user_courses => { :passed => true })
  scope :failed, where(:user_courses => { :passed => false })
  scope :new_courses, where(:user_courses => { :passed => nil })

  searchable do
    text :name, :content, :description
    text :lessons do
      lessons.map(&:name)
    end
    text :category do
      category.name
    end
    text :videos do
      videos.map(&:title)
    end
    text :documents do
      documents.map(&:name)
    end
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  has_many :user_lessons
  has_many :users, :through => :user_lessons
  has_many :testings
  has_many :videos
  has_many :documents

  def next
    course.lessons.where("id > ?", id).first
  end

  def prev
    course.lessons.where("id < ?", id).first
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :testing
  has_many :answers

  has_many :user_questions
  has_many :users, :through => :user_questions

  def next
    testing.questions.where("id > ?", id).first
  end

  def prev
    testing.questions.where("id < ?", id).first
  end
  
end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base

  has_many :users, :as => :students

  has_many :student_group_courses
  has_many :courses, :through => :student_group_courses

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :student_groups
  belongs_to :user
end

app/models/testing.rb
class Testing < ActiveRecord::Base
  has_many :questions
  has_many :answers, :through => :questions

  has_many :user_testings
  has_many :users, :through => :user_testings
  
  belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :assigned_user_courses, :class_name => 'UserCourse', :foreign_key => 'created_by_id', :inverse_of => :user_course
  has_many :assigned_courses, :source => :assigned_user_course, :through => :assigned_user_courses

  has_many :teachers

  belongs_to :student_group

  has_many :user_courses
  has_many :courses, :through => :user_courses

  has_many :user_lessons
  has_many :lessons, :through => :user_lessons

  has_many :user_questions
  has_many :questions, :through => :user_questions
    
  has_many :user_testings
  has_many :testings, :through => :user_testings

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :user_courses
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	validates_uniqueness_of :user_id, :scope => [:course_id]
	belongs_to :user
	belongs_to :course
  belongs_to :assigned_user_course, :class_name => 'User', :foreign_key => 'created_by_id'
end

app/models/user_lesson.rb
class UserLesson < ActiveRecord::Base
	validates_uniqueness_of :user_id, :scope => [:lesson_id]
	belongs_to :user
	belongs_to :lesson
end

app/models/user_question.rb
class UserQuestion < ActiveRecord::Base
	validates_uniqueness_of :user_id, :scope => [:question_id]
  belongs_to :user
  belongs_to :question
end

app/models/user_testing.rb
class UserTesting < ActiveRecord::Base
	validates_uniqueness_of :user_id, :scope => [:testing_id]
  belongs_to :user
  belongs_to :testing
  belongs_to :course
end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :lesson

  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)

  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => "oleghaidul@gmail.com", :password => "123@Fclcz", :dev_key => "AI39si4XUtMEqXcn-5JUfCKXQKenTWQwiLlYUJOviU5XHyCgEDrVQ56C84DzP6aoteqiP-edT42l_Zd3pn1_pMsOPX-SQMyYfA")
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(video, params)
    yt_session.video_update(video.yt_video_id, video_options(params))
    video.update_attributes(params)
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end

  private

    def self.video_options(params)
      opts = {:title => params[:title],
             :description => params[:description],
             :category => "People",
             :keywords => ["test"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_filter :authenticate_user!
  add_breadcrumb "Home", :root_path

  def index
    @courses = current_user.courses
    add_breadcrumb "Statistics", statistics_path
  end

  def courses
  	@courses = current_user.courses
  end

  def testings
  	@testings = current_user.testings
  end

  def questions
  	@questions = current_user.questions
  end

  %w[passed failed new_courses].each do |status|
    define_method status.to_s do
      @courses = current_user.courses.send(status)
      add_breadcrumb "Statistics", statistics_path
      add_breadcrumb status.capitalize, "/statistics/#{status}"
      render :index
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/statistics/_courses.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Test name</th>
      <th>Passed?</th>
      <th>Right Questions</th>
      <th>Wrong Questions</th>
    </tr>
  </thead>
  <tbody>
    <% course.user_testings.each do |t| %>
      <tr>
        <td><%= t.testing.name %></td>
        <td><%= t.passed? %></td>
        <td><%= link_to current_user.user_questions.where(:testing_id => t.testing, :correct => true).count, "#rightQuestions", :"data-toggle" => "modal" %></td>
        <td><%= link_to current_user.user_questions.where(:testing_id => t.testing, :correct => false).count, "#wrongQuestions", :"data-toggle" => "modal" %></td>
      </tr>

      <div class="modal fade" id="rightQuestions">
        <div class="modal-header">
          <a class="close" data-dismiss="modal">×</a>
          <h3>Right Questions</h3>
        </div>
        <div class="modal-body">
          <% current_user.user_questions.where(:testing_id => t.testing, :correct => true).each do |q| %>
            <h3><%= q.question.name %></h3>
            <% q.question.answers.each do |a| %>
              <% if q.answer_id == a.id && a.correct? %>
                <p><span class="label label-success"><%= a.name %></span></p>
              <% elsif q.answer_id == a.id && !a.correct? %>
                <p><span class="label label-important"><%= a.name %></span></p>
              <% elsif a.correct? %>
                <p><span class="label label-success"><%= a.name %></span></p>
              <% else %>
                <p><span class="label"><%= a.name %></span></p>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
      </div>

      <div class="modal fade" id="wrongQuestions">
        <div class="modal-header">
          <a class="close" data-dismiss="modal">×</a>
          <h3>Right Questions</h3>
        </div>
        <div class="modal-body">
          <% current_user.user_questions.where(:testing_id => t.testing, :correct => false).each do |q| %>
            <h3><%= q.question.name %></h3>
            <p>Note: <span class="label label-success">Right Answer</span>
                     <span class="label label-important">Your Answer</span></p>
            <% q.question.answers.each do |a| %>
              <% if q.answer_id == a.id && a.correct? %>
                <p><span class="label label-success"><%= a.name %></span></p>
              <% elsif q.answer_id == a.id && !a.correct? %>
                <p><span class="label label-important"><%= a.name %></span></p>
              <% elsif a.correct? %>
                <p><span class="label label-success"><%= a.name %></span></p>
              <% else %>
                <p><span class="label"><%= a.name %></span></p>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
      </div>
    <% end %>
  </tbody>
</table>

app/views/statistics/_lessons.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Lessons</th>
      <th>Passed?</th>
    </tr>
  </thead>
  <tbody>
    <% course.user_lessons.each do |l| %>
      <tr>
        <td><%= link_to l.lesson.name, "#demo-#{l.lesson.id}", :"data-toggle" => "collapse" %></td>
        <td><%= l.passed? %></td>
      </tr>
      <tr>
        <td colspan="5">
          <div id="demo-<%= l.lesson.id %>" class="accordion-toggle collapse" style="height: 0px;">
            <%= render "courses", :course => course %> 
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statistics/courses.html.erb
<% if @courses.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Total time</th>
        <th>Difficulty</th>
        <th>
          Collapse
        </th>  

        
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= link_to course.name, "#demo-#{course.id}", :"data-toggle" => "collapse" %></td>
          <td><%= link_to course.category.name, course.category if course.category %></td>
          <td><%= course.total_time %></td>
          <td></td>
          <% if current_user && current_user.courses.include?(course) %>
            <td><%= link_to "Remove course", user_course_path(:id => course), :class => "btn btn-danger", :method => :delete, :confirm => "Are you sure?" %></td>
          <% elsif current_user %>
            <td><%= link_to "Add course", user_courses_path(:id => course), :class => "btn btn-success", :method => :post %></td>
          <% end %>
        </tr>
        <tr>
          <td colspan="5">
            <div id="demo-<%= course.id %>" class="accordion-toggle collapse" style="height: 0px;">
              <%= render "courses", :course => course %> 
            </div>
          </td>
        </tr>
        
      <% end %>
    </tbody>
  </table>
<% else %>
  No courses found
<% end %>

<%= content_for :sidebar do %>
  <div class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">
        Statistics category
      </li>
      <li class="active"><%= link_to "Courses", courses_statistic_path(current_user) %></li>
      <li><%= link_to "Tests", testings_statistic_path(current_user) %></li>
      <li><%= link_to "Questions", questions_statistic_path(current_user) %></li>
    </ul>
  </div>
<% end %>

app/views/statistics/index.html.erb
<% if @courses.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Total time</th>
        <th>Difficulty</th>
        <th>Passed?</th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= link_to course.name, "#demo-#{course.id}", :"data-toggle" => "collapse" %></td>
          <td><%= link_to course.category.name, course.category if course.category %></td>
          <td><%= course.total_time %></td>
          <td></td>
          <td><%= current_user.user_courses.where(:course_id => course).first.passed %></td>
        </tr>
        <tr>
          <td colspan="5">
            <div id="demo-<%= course.id %>" class="accordion-toggle collapse" style="height: 0px;">
              <%= render "lessons", :course => course %> 
            </div>
          </td>
        </tr>
        
      <% end %>
    </tbody>
  </table>
<% else %>
  No courses found
<% end %>

<%= content_for :sidebar do %>
  <div class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">
        Statistics category
        <li><%= link_to "Passed courses", [:passed, :statistics] %></li>
        <li><%= link_to "Failed courses", [:failed, :statistics] %></li>
        <li><%= link_to "New courses", [:new_courses, :statistics] %></li>
      </li>
    </ul>
  </div>
<% end %>

app/views/statistics/passed.html.erb
<%= content_for :sidebar do %>
  <div class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">
        Statistics category
        <li><%= link_to "Passed courses", [:passed, :statistics] %></li>
        <li>Failed courses</li>
        <li>New courses</li>
      </li>
    </ul>
  </div>
<% end %>

<% if @courses.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Total time</th>
        <th>Difficulty</th>
        <th>Passed?</th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= link_to course.name, "#demo-#{course.id}", :"data-toggle" => "collapse" %></td>
          <td><%= link_to course.category.name, course.category if course.category %></td>
          <td><%= course.total_time %></td>
          <td></td>
          <td><%= current_user.user_courses.where(:course_id => course).first.passed? %></td>
        </tr>
        <tr>
          <td colspan="5">
            <div id="demo-<%= course.id %>" class="accordion-toggle collapse" style="height: 0px;">
              <%= render "lessons", :course => course %> 
            </div>
          </td>
        </tr>
        
      <% end %>
    </tbody>
  </table>
<% else %>
  No courses found
<% end %>

app/views/statistics/questions.html.erb
<%= content_for :sidebar do %>
  <div class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">
        Statistics category
      </li>
      <li><%= link_to "Courses", courses_statistic_path(current_user) %></li>
      <li><%= link_to "Tests", testings_statistic_path(current_user) %></li>
      <li class="active"><%= link_to "Questions", questions_statistic_path(current_user) %></li>
    </ul>
  </div>
<% end %>

app/views/statistics/testings.html.erb
<%= content_for :sidebar do %>
  <div class="span3">
    <ul class="nav nav-list">
      <li class="nav-header">
        Statistics category
      </li>
      <li><%= link_to "Courses", courses_statistic_path(current_user) %></li>
      <li class="active"><%= link_to "Tests", testings_statistic_path(current_user) %></li>
      <li><%= link_to "Questions", questions_statistic_path(current_user) %></li>
    </ul>
  </div>
<% end %>