config/routes.rb
Diplom::Application.routes.draw do

  get "student_groups/index"

  get "student_groups/show"

  get "students/index"

  get "students/show"

  get "documents/show"

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => 'home#index'

  resources :courses, :only => [:index, :show] do
    resources :lessons, :only => [:index, :show] do
      resources :testings do
        member do
          get :next
          get :results
        end
      end
      member do
        get :videos
        get :documents
        get :tests
      end
    end
  end

  resources :documents, only: :show

  resources :teachers do
    resources :students, :student_groups, :courses
  end

  resources :user_courses do
    collection do 
      post :bulk
    end
  end

  resources :categories, :study_rooms

  match 'search' => 'courses#search', :as => :search

  

  resources :statistics do
    member do
      get :courses
      get :testings
      get :questions
    end
    collection do
      get :passed
      get :failed
      get :new_courses
    end
  end

  resources :videos do
    member do
      post :add_comment
    end     
    new do
       post :upload
       get  :save_video
     end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :lesson

  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)

  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => "oleghaidul@gmail.com", :password => "123@Fclcz", :dev_key => "AI39si4XUtMEqXcn-5JUfCKXQKenTWQwiLlYUJOviU5XHyCgEDrVQ56C84DzP6aoteqiP-edT42l_Zd3pn1_pMsOPX-SQMyYfA")
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(video, params)
    yt_session.video_update(video.yt_video_id, video_options(params))
    video.update_attributes(params)
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end

  private

    def self.video_options(params)
      opts = {:title => params[:title],
             :description => params[:description],
             :category => "People",
             :keywords => ["test"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end
end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base

  def upload
    @video = Video.create(params[:video])
    if @video
      @upload_info = Video.token_form(params[:video], save_video_new_video_url(:video_id => @video.id))
    else
      respond_to do |format|
        format.html { render "/videos/new" }
      end
    end
  end

  def update
    @video     = Video.find(params[:id])
    @result    = Video.update_video(@video, params[:video])
    respond_to do |format|
      format.html do
        if @result
          redirect_to @video, :notice => "video successfully updated"
        else
          respond_to do |format|
            format.html { render "/videos/_edit" }
          end
        end
      end
    end
  end

  def save_video
    @video = Video.find(params[:video_id])
    if params[:status].to_i == 200
      @video.update_attributes(:yt_video_id => params[:id].to_s, :is_complete => true)
      Video.delete_incomplete_videos
    else
      Video.delete_video(@video)
    end
    redirect_to videos_path, :notice => "video successfully uploaded"
  end

  def destroy
    @video = Video.find(params[:id])
    if Video.delete_video(@video)
      flash[:notice] = "video successfully deleted"
    else
      flash[:error] = "video unsuccessfully deleted"
    end
    redirect_to videos_path
  end

  def add_comment
    @video = Video.find(params[:id])
    if @video.create_comment(params[:video][:comment])
      flash[:notice] = "Comment has been sucessfully added."
    else
      flash[:error] = "Sorry the comment has not been added."
    end
    redirect_to @video    
  end

  protected
    def collection
      @videos ||= end_of_association_chain.completes
    end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="group">
    <%= f.label :title, t("activerecord.attributes.video.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Add title video</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.video.description", :default => "Description"), :class => :label %>
    <%= f.text_field :description, :class => 'text_field' %>
    <span class="description">Add description video</span>
  </div>

<div class="group navform wat-cf">
<% if @video.new_record?%>
  <button class="button" type="submit">
    Save
  </button>
<%else%>
  <button class="button" type="submit">
    Save
  </button>
<%end%>

  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to "Cancel", videos_path, :class => "text_button_padding link_button" %>
</div>

app/views/videos/_sidebar.html.erb
<%= content_for :sidebar do %>
  <div class="span3">
    <div class="well sidebar-nav">
      <ul class="nav nav-list">
        <li><%= link_to "List", videos_path %></li>
        <li><%= link_to "New", new_video_path %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/videos/_video.html.erb
<%= raw yt_client.my_video(video.yt_video_id).embed_html %>

app/views/videos/edit.html.erb
<div class="block">     
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Video</h2>
    <div class="inner">
      <%= form_for @video, :url => video_path(@video), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<%= render "sidebar" %>

app/views/videos/index.html.erb
<div class="block">
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Videos</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.video.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @videos.each do |video| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= video.id %>
          </td>
                    <td>
            <%= link_to video.title, video_path(video) %>
          </td>
                    <td>
            <%= video.created_at %>
          </td>
          <td class="last">
            <%= link_to "Show", video_path(video) %> |
            <%= link_to "Edit", edit_video_path(video) %> |
            <%= link_to "Delete", video_path(video), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </di6v>
</div>

<%= render "sidebar" %>

app/views/videos/new.html.erb
<div class="block">         
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Video</h2>
    <div class="inner">
      <p>Step 1: add information about your video.</p>
      <%= form_for @video, :url => upload_new_video_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<%= render "sidebar" %>

app/views/videos/show.html.erb
<div class="block">        
  <div class="content">
    <div class="inner">
      
        <p>
          <%= raw yt_client.my_video(@video.yt_video_id).embed_html %>
        </p>
        <h3><%= @video.description %></h3>
        <p><b>url:</b> <a href="http://www.youtube.com/watch?v=<%= @video.yt_video_id %>&feature=youtube_it" target="_blank">http://www.youtube.com/watch?v=<%= @video.yt_video_id %></a></p>

      <div class="wat-cf">
        <%= link_to "Edit", edit_video_path(@video), :class => "button" %> 
        <%= link_to "Delete", video_path(@video), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>

</div>


<%= render "sidebar" %>

app/views/videos/upload.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Video</h2>
    <div class="inner">
      <p>Step 2: upload a new video.</p>

      <%= form_tag @upload_info[:url], :multipart => true do %>
        <%= hidden_field_tag :token, @upload_info[:token] %>
        <%= label_tag :file %>
        <%= file_field_tag :file %>
        <%= submit_tag "Upload video" %>
      <% end %>    
    </div>
  </div>
</div>